# Generated by Django 4.2.23 on 2025-07-13 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг(ссылка)')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Цена')),
                ('discount_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Цена по скидке')),
                ('is_new', models.BooleanField(default=True, help_text='Будет ли товар отображаться в блоке "Новинки"', verbose_name='Новинка')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('country', models.CharField(max_length=20, verbose_name='Страна производства')),
                ('size', models.CharField(max_length=20, verbose_name='Размеры')),
                ('full_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес')),
                ('product_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес/объём продукта')),
                ('categories', models.ManyToManyField(related_name='products', to='store.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные товары',
            },
        ),
    ]
