# Generated by Django 4.2.23 on 2025-07-14 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('pk',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ('-pk',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Помада!??!?!?!', max_length=96, verbose_name='Тип продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Ссылка/Адрес категории', unique=True, verbose_name='Слаг'),
        ),
    ]
