# Generated by Django 4.2.23 on 2025-09-03 21:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'Создан'), ('P', 'Оплачен'), ('S', 'Отправлен'), ('C', 'Отменён')], default='N', max_length=1, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('operation_id', models.CharField(max_length=96, verbose_name='ID операции')),
                ('payment_link', models.CharField(max_length=96, verbose_name='Сслыка на оплату')),
                ('shipping_address', models.TextField(max_length=96, verbose_name='Адрес доставки')),
                ('tracking_number', models.IntegerField(blank=True, null=True, verbose_name='Трек-номер')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': ('Заказ',),
                'verbose_name_plural': ('Заказы',),
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': ('Промокод',),
                'verbose_name_plural': ('Промокоды',),
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_orders', to='store.product')),
            ],
            options={
                'verbose_name': ('Продукт в заказе',),
                'verbose_name_plural': 'Продукты в заказе',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='store.ProductOrder', to='store.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_orders', to='store.promocode', verbose_name='Промокод'),
        ),
    ]
