# Generated by Django 4.2.23 on 2025-07-11 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_full_weight_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес/объём продукта'),
        ),
    ]
