# Generated by Django 4.2.23 on 2025-07-13 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Цена'))], verbose_name='Цена по скидке'),
        ),
    ]
