# Generated by Django 4.2.23 on 2025-09-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_promocode_productorder_order_items_order_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('pk',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Продукт в заказе', 'verbose_name_plural': 'Продукты в заказе'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ('code',), 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
