# Generated by Django 4.2.23 on 2025-07-15 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_options_alter_favorites_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='effect',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Эффект'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Размеры'),
        ),
    ]
