# Generated by Django 4.2.23 on 2025-09-07 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_alter_order_options_alter_productorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ('code', 'percent'), 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='percent',
            field=models.IntegerField(default=10, help_text='Процент скидки', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Процент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True, help_text='Определяет возможно ли использовать данный промокод', verbose_name='Дествителен'),
        ),
    ]
