# Generated by Django 4.2.23 on 2025-07-13 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Будет ли товар отображаться в блоке "Новинки"', verbose_name='Новинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Цена по скидке'),
        ),
    ]
