# Generated by Django 4.2.23 on 2025-07-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_collection_product_color_product_effect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.category')),
                ('categories', models.ManyToManyField(related_name='sections', to='store.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'Разделы',
            },
            bases=('store.category',),
        ),
    ]
