# Generated by Django 4.2.23 on 2025-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_new_alter_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Будет ли товар отображаться в блоке "Новинки"', verbose_name='Новинка'),
        ),
    ]
