# Generated by Django 4.2.23 on 2025-09-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_promocode_options_promocode_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ('percent',), 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_price',
            field=models.PositiveIntegerField(default=0, help_text='Минимальная цена товаров в корзине для активации промокода', verbose_name='Порог активации'),
        ),
    ]
