# Generated by Django 4.2.23 on 2025-11-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_slug_alter_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш'),
        ),
    ]
