# Generated by Django 4.2.23 on 2025-11-06 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productimage_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Объём продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес продукта'),
        ),
    ]
