# Generated by Django 4.2.23 on 2026-06-13 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_volume_alter_product_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес, г.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Вес продукта, г.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Объём продукта, мл.'),
        ),
    ]
