# Generated by Django 4.2.23 on 2026-07-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_paymentattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentattempt',
            options={'ordering': ('-pk',), 'verbose_name': 'Попытка оплаты', 'verbose_name_plural': 'Попытки оплаты'},
        ),
        migrations.RenameIndex(
            model_name='paymentattempt',
            new_name='store_payme_order_i_f0f3fa_idx',
            old_name='store_payme_order_i_1af546_idx',
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='idempotency_key',
            field=models.UUIDField(editable=False, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='operation_id',
            field=models.CharField(blank=True, max_length=96, null=True, unique=True, verbose_name='ID операции'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='store.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='payment_link',
            field=models.URLField(blank=True, max_length=512, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='provider_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='Статус платёжного провайдера'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Запрос к провайдеру'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ответ провайдера'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'Создание платежа'), ('link_created', 'Ссылка создана'), ('paid', 'Оплачен'), ('expired', 'Истёк'), ('failed', 'Ошибка создания'), ('unknown', 'Требует сверки'), ('refunding', 'Возврат выполняется'), ('refunded', 'Возвращён')], db_index=True, default='pending', max_length=16, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
