# Generated by Django 4.2.23 on 2025-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=96, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено, пользователь не может войти в аккаунт', verbose_name='Статус')),
                ('is_staff', models.BooleanField(default=False, help_text='Если включено, пользователь может войти в админ-панель', verbose_name='Статус администратора')),
                ('cart', models.ManyToManyField(blank=True, related_name='in_cart_of', through='store.Cart', to='store.product', verbose_name='Корзина')),
                ('fav', models.ManyToManyField(blank=True, related_name='fav_by', through='store.Favorites', to='store.product', verbose_name='Избранное')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('pk',),
            },
        ),
    ]
